### ISSUE TITLE
The plot rotates with changing the date

### ISSUE THREAD

**Issue by MohamedNedal** [jgieseler/solarmach#11]
Hi, I noticed that once the date and time are changed, the polar plot rotates and it's no longer adjusted as shown in the example notebook (i.e., the 90 deg. points upward, 0 deg. points to the right, etc.). 
Is there a workaround to make the polar plot fixed when changing the date and time? 
Also I don't know why the grid circles disappear 

![image](https://user-images.githubusercontent.com/43330567/171503885-f4d7a550-436c-42ed-9917-e9b63cf5e90f.png)

![image](https://user-images.githubusercontent.com/43330567/171503981-666203bf-c64f-458b-ae4f-1e526862e305.png)

**Comment by jgieseler** [comment]
> Hi, I noticed that once the date and time are changed, the polar plot rotates and it's no longer adjusted as shown in the example notebook (i.e., the 90 deg. points upward, 0 deg. points to the right, etc.).
> Is there a workaround to make the polar plot fixed when changing the date and time?

This is the expected behavior. With default settings, the longitudes are provided in [Carrington coordinates](https://www.oxfordreference.com/view/10.1093/oi/authority.20110803095551605) ([more details at SunPy](https://docs.sunpy.org/en/stable/code_ref/coordinates/carrington.html)). In this system, lines of longitude rotate with the Sun. And by default we plot the Earth at "6 o'clock", so downwards. Of course, one could define the plot in such a way that 0° Carrington longitude is always at "6 o'clock", but I doubt this brings any advances. Because then we would have the longitude values fixed, but _all_ spacecraft would rotate 'wildly'.

> Also I don't know why the grid circles disappear.

Me neither. :wink:  This is already opened as #5

**Comment by jgieseler** [comment]
I forgot to mention that you can in addition plot the Stoneyhurst coordinate system as an overlay (in green, see below). This coordinate system will stay fixed. It's planned to be included directly in solarmach, cf. #1 where you can also find a code example.

![image](https://user-images.githubusercontent.com/39489154/171625576-2aa38479-e61b-4f92-92e9-cf1729c3a90f.png)

**Comment by MohamedNedal** [comment]
> I forgot to mention that you can in addition plot the Stoneyhurst coordinate system as an overlay (in green, see below). This coordinate system will stay fixed. It's planned to be included directly in solarmach, cf. #1 where you can also find a code example.
> 
> ![image](https://user-images.githubusercontent.com/39489154/171625576-2aa38479-e61b-4f92-92e9-cf1729c3a90f.png)

Yes I saw that. The reason why I mentioned the fixed degrees and rotating spirals would be easier to follow by eye is that, for instance, to be in the same way as the ENLIL-WSA model showing the Parker spirals with the evolution of the solar wind. 

![image](https://user-images.githubusercontent.com/43330567/171629139-1b6a3925-d7fe-4457-9578-16a6a5615f68.png)

**Comment by MohamedNedal** [comment]
@jgieseler  Could you please mention how could we define the plot in such a way that 0° Carrington longitude is always at "6 o'clock"? Which part of the code should be modified?

**Comment by jgieseler** [comment]
Here as an animation using Carringtion coordinates with 0° Carrington longitude fixed at 3 o'clock:

![solarmach](https://user-images.githubusercontent.com/39489154/171644764-a21319d3-1fe3-42f7-945d-0aff84ae789c.gif)

This is achieved by just removing [L354 from solarmach/__init__.py](https://github.com/jgieseler/solarmach/blob/main/solarmach/__init__.py#L354)
