### ISSUE TITLE
Plot distance projected to the ecliptic plane instead of radial distance (optionally)

### ISSUE THREAD

**Issue by jgieseler** [jgieseler/solarmach#3]
At the moment, Solar-MACH shows the configuration plot only with respect to _longitude_ and _radius_. For high latitude orbits (e.g., Solar Orbiter), it might be worthwhile to (optionally) plot the _distance projected to the ecliptic plane_ instead of the _radial distance_ (in spherical coordinates). So in the following picture (where _x, y_ span the ecliptic), using **r** instead of **ρ**:

<img src="https://user-images.githubusercontent.com/39489154/169517545-c51c1490-4434-41cb-8809-a0ef246cde00.png" width="400">

([Figure source](https://www.researchgate.net/figure/Figure-A1-Spherical-coordinate-system_fig10_281208759). Note that this picture plots the colatitude _ф_, and not the latitude, which would be 90-_ф_)

Thanks to @AthKouloumvakos for the idea

**Comment by jgieseler** [comment]
Maybe rather plot the distance projected to the _heliographic equatorial plane_ (instead of _ecliptic plane_)? :thinking:

**Comment by jgieseler** [comment]
`SolarMACH.plot()` now has a new option, `plot_distance`. It is by default `'heliographic-equator'`, i.e., for plotting the spherical radius is projected to the heliographic equatorial plane. For backwards-compatibility (and testing), `plot_distance='heliographic-radius'` provides the previous behavior, i.e., as distance in the polar plot the value of the actual spherical radius is used.

In the following example, **Ulysses** coordinates are:
``` python
>>> sm.body_dict['Ulysses'][3]
<SkyCoord (HeliographicStonyhurst: obstime=2021-10-20T00:00:00.000, rsun=695700.0 km): 
    (lon, lat, radius) in (deg, deg, AU)
    (124.84379058, 25.40222722, 4.42381195)>
```
To obtain the projected distance in the heliographic equatorial plane, the `SkyCoord` object is given in cylindrical coordinates:
``` python
>>> sm.body_dict['Ulysses'][3].cylindrical
<CylindricalRepresentation (rho, phi, z) in (AU, deg, AU)
    (3.9961117, 124.84379058, 1.89768371)>
```
Here, `rho` is equal to `radius * cos(lat) = 3.9961117 AU`

`plot_distance='heliographic-radius'`:
![image](https://user-images.githubusercontent.com/39489154/199988394-7e13d5b1-9514-432d-a53a-f9793a2710ab.png)

 `plot_distance='heliographic-equator'`:
![image](https://user-images.githubusercontent.com/39489154/199988348-56602498-19e7-45b9-8291-09961611d14f.png)

**Comment by jgieseler** [comment]
Note that for calculating the Parker spiral, the distance projected to the heliographic equatorial plane is used together with the solar rotation according to the actual heliographic latitude! Thus, we get the latitude-dependent Parker spiral (blue and red curve in the following plot) projected to the heliographic equatorial plane (black curve):
![image](https://user-images.githubusercontent.com/39489154/199997984-6b44c8a9-2bd6-4482-8035-66824a34be8c.png)
(From _Sternal, O., 2010. Transport of galactic cosmic rays in different heliospheric magnetic field configurations_, https://macau.uni-kiel.de/receive/diss_mods_00005136)

**Comment by jgieseler** [comment]
Update: With https://github.com/jgieseler/solarmach/commit/5196c78e0c08b5fe43a75ec0ab75a464069ff1e7, all calculations are carried out in spherical coordinates. Only for the two-dimensional visualization, the coordinates are projected to the heliographic equatorial plane. In the course of this last commit, the `plot_distance` option has been removed!

**Comment by AthKouloumvakos** [comment]
So, by default the plot will be made in the 'heliographic-equator' mode?

**Comment by jgieseler** [comment]
Yes! Before it was actually a mix of two coordinate systems, so it doesn't make sense to continue that.

Of course, one could think of providing another (optional) coordinate system...
