### ISSUE TITLE
Use figure tests to validate plot output

### ISSUE THREAD

**Issue by wtbarnes** [jgieseler/solarmach#50]
Currently, the results of the plotting tests are only validated by checking for the existence of the plot, e.g. https://github.com/jgieseler/solarmach/blob/9a6ab68e047a43b529c94ff4f73ec10697836654/solarmach/tests/test.py#L81. This provides no guarantee as to the correctness of this plot. I would suggest using figure tests to validate the output of these plotting methods. For more details on how this could work, see [this section of the SunPy dev guide](https://docs.sunpy.org/en/latest/dev_guide/contents/tests.html#figure-unit-tests).

**Comment by jgieseler** [comment]
Yes, the test setup for the figures was just a workaround. Thanks for the link to the sunpy dev guide, that gave me a good starting point! 

I now included (and verified) hash-checking via `pytest-mpl`: 

https://github.com/jgieseler/solarmach/blob/ce213d68b4bcbd6873e659073bdc7d0da196f4bb/solarmach/tests/test.py#L69-L70
https://github.com/jgieseler/solarmach/blob/ce213d68b4bcbd6873e659073bdc7d0da196f4bb/tox.ini#L37
https://github.com/jgieseler/solarmach/blob/ce213d68b4bcbd6873e659073bdc7d0da196f4bb/.github/workflows/pytest.yml#L30
