### ISSUE TITLE
Adding the figure to another figure + stopping the fig from showing up

### ISSUE THREAD

**Issue by MohamedNedal** [jgieseler/solarmach#55]
Hello, I have two questions, please.

1. How can I stop the output figure from showing up? Is there an option to just return the `fig, ax` objects of `sm.plot` without showing the figure itself?

2. How can I add the output figure to a `matplotlib.axes._subplots.AxesSubplot` object to show the figure in another subplot figure? I tried the code below but I was wondering if there was a more efficient way to do that.

Here's the code I tried:

```python
from solarmach import SolarMACH
import matplotlib.pyplot as plt

body_list = ['Earth', 'Mars', 'STEREO-A', 'PSP', 'Solo']
vsw_list = []                                    # leave empty to obtain measurements
date_solmach = '2021-06-07'

coord_sys = 'Stonyhurst'                         # 'Carrington' (default) or 'Stonyhurst'
reference_long = None                            # longitude of reference (None to omit)
reference_lat = None                             # latitude of reference (None to omit)
reference_vsw = 400                              # define solar wind speed at reference
long_offset = 270                                # longitudinal offset for polar plot; defines where Earth's longitude is (by default 270, i.e., at "6 o'clock")
plot_spirals = True                              # plot Parker spirals for each body
plot_sun_body_line = False                       # plot straight line between Sun and body
return_plot_object = True                        # figure and axis object of matplotib are returned, allowing further adjustments to the figure
transparent = True                               # make output figure background transparent
numbered_markers = True                          # plot each body with a numbered marker

# initialize
sm = SolarMACH(date_solmach, body_list, vsw_list, reference_long, reference_lat, coord_sys)

# make plot
fig_solmach, ax_solmach = sm.plot(plot_spirals=plot_spirals,
                  plot_sun_body_line=plot_sun_body_line,
                  reference_vsw=reference_vsw,
                  transparent=transparent,
                  numbered_markers=numbered_markers,
                  long_offset=long_offset,
                  return_plot_object=return_plot_object,
                                  figsize=[17,10])


fig = plt.figure(figsize=[20,10])
ax = fig.add_subplot(331)
ax.imshow(fig_solmach.canvas.renderer.buffer_rgba())
ax.axes.xaxis.set_visible(False)
ax.axes.yaxis.set_visible(False)
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)
ax.spines['bottom'].set_visible(False)
ax.spines['left'].set_visible(False)

# Add more panels to the figure
# ..............................

plt.show()
```

**Comment by jgieseler** [comment]
>     1. How can I stop the output figure from showing up? Is there an option to just return the `fig, ax` objects of `sm.plot` without showing the figure itself?

No, unfortunately, there is no such direct option as of now. I'm wondering if it would make sense to deactivate the plot showing always if `return_plot_object =True` because usually one would only use that to do something with the plot... 🤔 

>     2. How can I add the output figure to a `matplotlib.axes._subplots.AxesSubplot` object to show the figure in another subplot figure? I tried the code below but I was wondering if there was a more efficient way to do that.

Hm, that's totally a matplotlib question. Never tried that myself, so I have no clue.

**Comment by MohamedNedal** [comment]
For (1), I managed to change it in the source code. For (2), I exported the figure as a `png` image and then imported it and showed it with `ax.imshow()`. Thank you @jgieseler , that's a nice update and makes it much easier to identify the objects in the plot!

**Comment by jgieseler** [comment]
I think for (1), I would just add `if not return_plot_object:` in the line before https://github.com/jgieseler/solarmach/blob/adc1b1747d9b3028216db7bed7b67d5978933a67/solarmach/__init__.py#L927

**Comment by MohamedNedal** [comment]
Thank you
