### ISSUE TITLE
Unpin matplotlib version in requirements

### ISSUE THREAD

**Issue by nabobalis** [jgieseler/solarmach#57]
Is there a need to pin MPL to one specific version?

**Comment by jgieseler** [comment]
Nothing serious. With one matplotlib update, the legend and annotation started to be misaligned and partly off the figure. That's why I pinned it to a previous working version, and haven't found the time to update the code to work with a recent version.

**Comment by nabobalis** [comment]
MPL does love to shift things around. The sunpy figure tests always have to be updated due to those issues.

**Comment by jgieseler** [comment]
My "problem" is that most solarmach users use the web version and/or don't update their packages if not explicitly needed, so no one complained so far. 😅

**Comment by nabobalis** [comment]
For context (which I did not provide at all), we are trying to construct a virtual environment with solarmach and a few other packages which have a higher min version of MPL. So we are hitting that.

**Comment by jgieseler** [comment]
Yeah, I was guessing something like this. Unfortunately my computer broke on Wednesday, so I'm a bit handicapped right now. Do you have a deadline for that project (like a summer school)?

**Comment by nabobalis** [comment]
It is no rush, we can increase the version of MPL in the env. We have like two plots and running some other solarmach functions, so at worst, some of the figures look different. It won't be a problem, so no need to work on this with any urgency.

**Comment by jgieseler** [comment]
Fixed with https://github.com/jgieseler/solarmach/releases/tag/v0.4.0

**Comment by nabobalis** [comment]
Thank you!
