### ISSUE TITLE
Fix plot position

### ISSUE THREAD

**Issue by jgieseler** [jgieseler/solarmach#7]
The position of the plot can vary slightly because of the moving Carrington longitude (with the additional Earth-centered coordinates plotted on top this doesn't happen). This might be a bit problematic if one wants to use multiple plots to make an animation ([example](https://i.imgur.com/coeT2pM.mp4)). 

=> Change the code to ensure that the plot always is at the same position in the figure.

**Comment by MohamedNedal** [comment]
@jgieseler  Is it possible to fix the numbers (degrees) and make the spiral arms rotate instead? I think that way would be more realistic and easier to check

**Comment by jgieseler** [comment]
> @jgieseler Is it possible to fix the numbers (degrees) and make the spiral arms rotate instead? I think that way would be more realistic and easier to check

Is this already answered with #11?
